P1

diff --git a/Project/Codes/Makefile b/Project/Codes/Makefile
--- a/Project/Codes/Makefile
+++ b/Project/Codes/Makefile
@@ -27,9 +27,48 @@ LIBS += $(GCCARM)/lib/gcc/arm-none-eabi/14.2.1/thumb/v7e-m+fp/hard/libgcc.a
 
 LDFLAGS = -T $(LINKER_SCRIPT) -Map system.map --entry Reset_Handler
 
+#########################################
+# Auto detect platform and flash
+# To override the default FLASHDIR, use: `make flash FLASHDIR=/path/to/flash`
+
+UNAME_S := $(shell uname -s)
+ifeq ($(UNAME_S),Linux)
+	IS_WSL := $(shell grep -qi microsoft /proc/version 2>/dev/null && echo 1 || echo 0)
+	ifeq ($(IS_WSL),1) # WSL
+		FLASHDIR ?= /mnt/c/Temp
+	else # Native Linux
+		FLASHDIR ?= /mnt/$(TARGET)
+	endif
+else ifeq ($(UNAME_S),Darwin) # macOS
+	FLASHDIR ?= /Volumes/$(TARGET)
+endif
+
 flash: $(TARGET).hex
-	cp $(TARGET).hex /mnt/c/Temp
-	(cd /mnt/c/Temp && cmd.exe /c copy $(TARGET).hex E:)
+ifeq ($(UNAME_S),Linux)
+ifeq ($(IS_WSL),1) # WSL
+	/bin/cp $(TARGET).hex "$(FLASHDIR)"
+	(cd "$(FLASHDIR)" && cmd.exe /c copy $(TARGET).hex E:)
+else # Native Linux
+	@if [ -d "$(FLASHDIR)" ]; then \
+		/bin/cp $(TARGET).hex "$(FLASHDIR)"; \
+		echo "Flashed to MICROBIT"; \
+	else \
+		echo "Flash failed: Mount not found at $(FLASHDIR)"; \
+	fi
+endif
+else ifeq ($(UNAME_S),Darwin) # macOS
+	@if [ -d "$(FLASHDIR)" ]; then \
+		/bin/cp $(TARGET).hex "$(FLASHDIR)"; \
+		echo "Flashed to MICROBIT"; \
+	else \
+		echo "Flash failed: Mount not found at $(FLASHDIR)"; \
+	fi
+else # Fallback
+	@echo "Unknown platform: $(UNAME_S)"
+	@exit 1
+endif
+
+#########################################
 
 $(TARGET).hex: $(TARGET).out
 	$(OBJCOPY) -O ihex $< $@
@@ -53,4 +92,9 @@ clean::
 
 startup.o: startup.c #Vector table and crt initialization
 system.o: system.c #clock initialization
-main.o: main.c bsp/bsp.h rtx/cmsis_os2.h 
+main.o: main.c bsp/bsp.h bsp/adc.h bsp/audio.h bsp/gpio.h bsp/ledbtn.h \
+ bsp/microbit.h bsp/printf.h bsp/pwm.h bsp/uart.h rtx/cmsis_os2.h
+motor_task.o: motor_task.c bsp/bsp.h bsp/adc.h bsp/audio.h bsp/gpio.h \
+ bsp/ledbtn.h bsp/microbit.h bsp/printf.h bsp/pwm.h bsp/uart.h \
+ bsp/microbit.h bsp2/bsp2.h bsp2/encoder.h bsp2/i2c.h bsp2/lsm303agr.h \
+ bsp2/motor.h bsp2/radio.h rtx/cmsis_os2.h
